#!/bin/bash

cd ~

alias apt='sudo apt-get --assume-yes install'

apt git curl lynx python3 python3-pip neovim python3-neovim exuberant-ctags fzf tldr

wget https://github.com/sharkdp/bat/releases/download/v0.12.1/bat-musl_0.12.1_amd64.deb
wget https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
wget https://github.com/sharkdp/fd/releases/download/v7.4.0/fd-musl_7.4.0_amd64.deb

apt ./bat-musl_0.12.1_amd64.deb ./ripgrep_11.0.2_amd64.deb ./fd-musl_7.4.0_amd64.deb

rm bat-musl_0.12.1_amd64.deb ./ripgrep_11.0.2_amd64.deb ./fd-musl_7.4.0_amd64.deb

pip3 install powerline-shell
nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
mkdir -p .local/share/nvim/session .vim/backup

